management:
  endpoints:
    enabled-by-default: true

# If you're using task bootRunLocal, the command line arguments in it
# will supercede this.
#server:
#  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - uri: https://google.ca/
        predicates:
          - Path=/google/{segment}
        filters:
          - SetPath=/{segment}
