# If you're using task bootRunLocal, the command line arguments in it
# will supercede this. To see the port on which bootRunLocal will run
# this service, go to this project's build.gradle.
server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - uri: http://localhost:8081/
        predicates:
          - Path=/hello/{segment}
        filters:
          - SetPath=/{segment}

---
spring:
  profiles: local

server:
  ssl:
    enabled: true
    key-alias: localhost_key
    key-store-password:
    key-store: classpath:localhost.p12
    key-store-type: PKCS12
